In [ ]:
import numpy as np

In [ ]:
# single dimensional Array
import numpy as np
n1=np.array([1, 2, 3, 4, 5])
n1

array([1, 2, 3, 4, 5])

In [ ]:
#Multi dimensional Array
import numpy as np
n2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
n2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#Zeros
n3=np.zeros((5,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#Full
n4=np.full((3,3),10)
n4

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
#Arrange
n5=np.arange(10,50,5)
n5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#Random
n6=np.random.randint(1,10,5)
n6

array([4, 8, 8, 1, 6])

In [ ]:
#Shape
n1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
n1.shape

(2, 5)

In [ ]:
n1.shape=(5,2)
n1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#vastack
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#hstack
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [ ]:
#coloumn Stack
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#intersected
n1=np.array([1,2,3,4,5])
n2=np.array([4,5,8,9,10])
np.intersect1d(n1,n2)

array([4, 5])

In [ ]:
#set diff
np.setdiff1d(n2,n1)

array([ 8,  9, 10])

In [ ]:
#sum of arrays
np.sum([n1,n2])

51

In [ ]:
#axis sum
np.sum([n1,n2],axis=0)
np.sum([n1,n2],axis=1)

array([15, 36])

In [ ]:
#array mathematics
import numpy as np
n7=np.array([1,2,3,4,5])
nb=n7+5
nb

array([ 6,  7,  8,  9, 10])

In [ ]:
nb=n7*2
nb

array([ 2,  4,  6,  8, 10])

In [ ]:
nb=n7-1
nb

array([0, 1, 2, 3, 4])

In [ ]:
nb=n7/2
nb

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
#mean
n1=([1,2,3,5,6])
np.mean(n1)

3.4

In [ ]:
#median
np.median(n1)

3.0

In [ ]:
#standard deviation
np.std(n1)

1.854723699099141

In [ ]:
# numpy matrix
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
#to show rows
n1[0]
n1[1]

array([4, 5, 6])

In [ ]:
#column
n1[:,0]

array([1, 4, 7])

In [ ]:
np.transpose(n1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
#Matrix multiplication
n2=([[10,11,12],[13,14,15],[16,17,18]])
n1.dot(n2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [ ]:
n1=np.array([1,2,3,4,5])
np.save('my_numpy',n1)

In [ ]:
np.load('my_numpy.npy')

array([1, 2, 3, 4, 5])